#FX
define particles_sprite = Fixed(SnowBlossom("fx/particles_sprite.png",10, xspeed=(-30, 30), yspeed=(-25, -50), start=5))
define eyeopen =  ImageDissolve("fx/eye.png", 1.0, 0)
define eyeclose = ImageDissolve("fx/eye.png", 1.0, 0, reverse=True)
define circlefx = ImageDissolve("fx/circlewipe-cw.jpg", 0.75, 8)
define ccirclefx = ImageDissolve("fx/circlewipe-ccw.jpg", 0.75, 8)
define goslow = ImageDissolve("fx/goslow.png", 2.0, 8)
define spellfx = ImageDissolve("fx/spellfx.jpg", 1.0, 8)
define storyfx = ImageDissolve("fx/storyfx.jpg",1.0, 8)
define peekfx = ImageDissolve("fx/peekfx.png",0.5, 8)
define rain1 = ImageDissolve("fx/rain1.jpg",1.0, 8)
define snow1 = ImageDissolve("fx/snow1.png",1.0, 8)
define wet = ImageDissolve("fx/wet.jpg", 1.0, 8)
define leafwipe = ImageDissolve("fx/leafwipe.jpg", 1.0, 8)
define shatter = ImageDissolve("fx/shatter.png", 1.0, 8)
define snakes = ImageDissolve("fx/snakes.png", 1.0, 8)
define dis08 = Dissolve(0.8)

define pushle = PushMove(0.3, "pushleft")
define pushri = PushMove(0.3, "pushright")
define pushu = PushMove(0.3, "pushup")
define pushuplong = PushMove(1, "pushup")
define pushuplong2 = PushMove(0.4, "pushup")
define pushdo = PushMove(0.2, "pushdown")
define pushdolong = PushMove(0.4, "pushdown")
define slidele = CropMove(0.5, "slideleft")
define fadesex = Fade(1, 0, 1, color='000000')
define flash = Fade(0.4, 0, 0.4, color='FFFFFF')
define flash2 = Fade(0.25, 0, 0.25, color='FFFFFF')

define w9 = ImageDissolve("fx/9.jpg", 1.5, 8)
define w17 = ImageDissolve("fx/17.png", 1.0, 8)
define w18 = ImageDissolve("fx/18.png", 1.0, 8)
define w21 = ImageDissolve("fx/21.jpg", 1.0, 8)
define w24 = ImageDissolve("fx/24.png", 1.0, 8)
define w33 = ImageDissolve("fx/33.png", 1.0, 8)
define w39 = ImageDissolve("fx/39.jpg", 1.0, 8)
define cw39 = ImageDissolve("fx/39.jpg", 1.0, 8, reverse=True)